[package]
name = "rstresser"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
reqwest = "0.11.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
